#!/bin/bash
#Author
#JoyGhosh
echo """
 (Tor Browser)
  For
 Kali Linux By Joy Ghosh                                             
"""
apt-get update
apt-get install alacarte
wget https://www.torproject.org/dist/torbrowser/8.0.6/tor-browser-linux64-8.0.6_en-US.tar.xz
tar xf tor-browser-linux64-8.0.6_en-US.tar.xz
echo 'Now Delete the start-tor-browser file from tor-browser-en-US/Browser And Move The start-tor-browser file from Torinstaller folder'
echo 'Script By Joy Ghosh<mail:joychondroghosh@gmail.com'
